// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3sJWuQBKiyNbKHjUt4Dj3DRfGQIPGts',
    appId: '1:649790097367:web:d052e30a30360a963b6d92',
    messagingSenderId: '649790097367',
    projectId: 'ooot-bwhi',
    authDomain: 'ooot-bwhi.firebaseapp.com',
    storageBucket: 'ooot-bwhi.appspot.com',
    measurementId: 'G-5DR3H23HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsecEU5FHg16VL-Z-mRu6B0FJKHBqZi8',
    appId: '1:649790097367:android:98d8756c2014b8e63b6d92',
    messagingSenderId: '649790097367',
    projectId: 'ooot-bwhi',
    storageBucket: 'ooot-bwhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQApGzZR4B6Gjz9uOR1z5TPzqvqvy4_k',
    appId: '1:649790097367:ios:bd8d4bc73f3aabca3b6d92',
    messagingSenderId: '649790097367',
    projectId: 'ooot-bwhi',
    storageBucket: 'ooot-bwhi.appspot.com',
    iosClientId: '649790097367-tpflcb8qfgihl9fm76u58fgo7tfh3bbb.apps.googleusercontent.com',
    iosBundleId: 'com.project9.bwhi.shea',
  );
}
