// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCSy2vm4WbVPDFPt_esTfmZOISifKrhE',
    appId: '1:348932262248:web:46d4964e7b83b273746edd',
    messagingSenderId: '348932262248',
    projectId: 'bwhi-36fe2',
    authDomain: 'bwhi-36fe2.firebaseapp.com',
    storageBucket: 'bwhi-36fe2.appspot.com',
    measurementId: 'G-FF7V30X13N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9Xt6bePLIchKdhDqhXBwSrCvxVON2b8',
    appId: '1:348932262248:android:80b31a3a4436c526746edd',
    messagingSenderId: '348932262248',
    projectId: 'bwhi-36fe2',
    storageBucket: 'bwhi-36fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFSwIbiuMu0kAmQTPjpPy7mYF5_uYejw',
    appId: '1:348932262248:ios:8a83fc36f2bc27ba746edd',
    messagingSenderId: '348932262248',
    projectId: 'bwhi-36fe2',
    storageBucket: 'bwhi-36fe2.appspot.com',
    iosClientId: '348932262248-c00t1o659kmivltldejsja9cb9m8uji3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shea',
  );
}
