// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUCv7MgTAIajA8-0icQx54XpgMXbOiqc',
    appId: '1:487471929955:web:92d00e57228c9f5fa47656',
    messagingSenderId: '487471929955',
    projectId: 'shea-ac999',
    authDomain: 'shea-ac999.firebaseapp.com',
    storageBucket: 'shea-ac999.appspot.com',
    measurementId: 'G-RG3PFP01PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DO4yog6ZwlF6MxsQCz4q6ErkcUjKfC4',
    appId: '1:487471929955:android:f07cefc4f681e348a47656',
    messagingSenderId: '487471929955',
    projectId: 'shea-ac999',
    storageBucket: 'shea-ac999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglwpZ7m4mvzJnP7NDVacgsRRZMQQuvsc',
    appId: '1:487471929955:ios:76aec8bdc012ebaca47656',
    messagingSenderId: '487471929955',
    projectId: 'shea-ac999',
    storageBucket: 'shea-ac999.appspot.com',
    androidClientId: '487471929955-ckbeihpalv7p2uhvqu4l5nbcs37ro9j0.apps.googleusercontent.com',
    iosClientId: '487471929955-vidgftdrr9pu59tm1e4r2qgts8i9lhc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shea',
  );
}
